{% set name = "python-snap" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://snap.stanford.edu/snappy/release/snap-4.1.0-4.1-centos6.5-x64-py2.6.tar.gz
  sha256: 94e556fdc8fd7642f80b7bb9e23262cb05576d4eb8d22bd654013cb9d5316f5d

build:
  number: 1000
  skip: True  # [not linux or not py27]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - snap

about:
  home: http://snap.stanford.edu/snap/
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/License.txt'
  summary: 'Snap.py is a Python interface for SNAP.'
  description: |
    Snap.py is a Python interface for SNAP. SNAP is a general purpose,
    high performance system for analysis and manipulation of large networks.
    SNAP is written in C++ and optimized for maximum performance and compact
    graph representation. It easily scales to massive networks with hundreds
    of millions of nodes, and billions of edges.
    Snap.py provides performance benefits of SNAP, combined with flexibility
    of Python. Most of the SNAP functionality is available via Snap.py in Python.
  doc_url: https://snap.stanford.edu/snappy/index.html#docs

extra:
  recipe-maintainers:
    - CurtLH
