travis:
  secure:
    BINSTAR_TOKEN: XkmrmuxQGW30F/Ns0bMspYRMN7i6/vVQrc3QN9WA5QSdQ6TY38eJRlEZS3ElEGp+rLYVvgY52MWWIENskNMOouewc9G3AxDg3IDUNM40giWz8pAoR6dPB7LLCtz9FwSf47OncdYLKR+XHQdvrBeWZ6kEjrx5f8nYApBgTr6/yNePNyqSy772pyA1gUkOV6vCNNzeCSkDRflERVgkCVpaDw28UsUgmgg12Y4mJsSlFMiYFnyn1eV129Kwp12Zz7QW+fvSGAsOPGMqO7SMOeWaVLkdGcPs3CwFvonYtO2V2hhThZmpUUOKgSHalsPlkbDsXp6BMBCsC+Ht8WiA+BobkIBijcNW/BDZGeIeABYv+luFX7Cq2MC0IbBb2PJNC5JLL99SigHk8rmH0Eq+d3V0qzYKaxVX/bJonkCq+nY9W5fxbnaJuJLE5NW5a1ILTW33KxJ4gh2teDwEnS8yUTPsCIjRA6LjUSvUoKHbTOHuDEzuODNai1nVo8F4j/GjnLAj8F3cqdogsfx7bdwfxjCUdN0RoY82qM75dYO3v4H0BC2D4dzIx2MjrZ1BWUAd4V3m5RQk1fChznbNadnXEm0/BJNKfw8iWoKGjH17CA0sC/G5fckmPsZi9i7flN3+UUzu1edu5Od8WiRNVcKk6xUI6AtB7HvcSfTSX6ff8CA6l+8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
