travis:
  secure:
    BINSTAR_TOKEN: P7QT+CsGmPAhAC/Pyd986bqYgRIC+ZwPrtkLY9mrcAhoJu3H2+jsqKSrgNaqf68kuGCNpapYh9K5QvVrqdGHpg5PD3BKzFbn/l6w22eILjLDNeutdOSMRS5K223ZosFCWuk50jyjYFu7pANSjc+7xWiis8NmHxixWu+/v6CksUXXju6Rxc++376SjmAz0fX88ww8moEimbcCAsvO7CnQG3a68s4VlBk2SpU8nENvcgFQ5ML6fetg+2/pwfvZ/izh8rmGRG0uQgC5qdB6w7WGIbQLHuA1Fflv/8wY0S8sfyeWG+5Hy2F0KJn88exLwEuBYsofeD5xOGyYshUfZCdHrsm47WSpwS4uh0Wwa6Jrboj8pkawxP/c5DnvMMctIUUOdpv1DCybsHPURVkLxPQRlCz7IAGDa5i0T7pCo96vdZNkHkBRSBm0GowQu06ImYZWugFVHRLC8GLfQbJyz0/KJh+Xc0g10IMtZbJ7MpvZnvK2oaPmANrYhbpjiLPBQDDfdfZvZ4zQJNYm1otGLoqqpnFNy3aacy0XDlqQ1+OoSb0HuZdk/8VRe0L+4s1BjqcQi3T6+UllwFcjrTBnyScaVMfGrC0CZ8v0VCKZDLc95R7z6YL5UVorScOr83Z9YJrWcsn5kfWq3nSCSF9L/feJT5Qa8URBIJGmqnicvH+d4xs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
